resources:
  cloud: gcp
  accelerators: A100-80GB:1
  memory: 64+
  disk_size: 256
  use_spot: true # Use spot instances to save costs but understand that they can be terminated at any time.
  ports: 8888
  any_of:
    - region: us-east4
    - region: us-central1

file_mounts:
  ~/sky_workdir/.env: ./.env
  ~/.gitconfig: ~/.gitconfig

workdir: .

setup: |
  echo -e "\n==================   SKYPILOT SETUP   ==================\n"

  echo -e "\n=========   Creating .bashrc file...   =========\n"
  cat << 'EOF' >> ~/.bashrc
  #!/usr/bin/env bash

  # -------------- Aliases --------------
  # General
  alias fzfenv="printenv | fzf | cut -d '=' -f 2"
  alias fzfhist="history | fzf --tac | sed 's/^[[:space:]]*[0-9][0-9]*[[:space:]]*//'"
  alias fzfps="ps u | fzf"
  alias duf="du -sh ./* | sort -hr"
  alias dud="du -h -d 1 | sort -hr"

  # Git
  alias fzfgc="git branch | fzf | xargs git checkout"
  alias fzfgl="git log --oneline | fzf"
  alias glg="git log --oneline --graph --decorate"

  # Python
  alias avenv="source .venv/bin/activate"
  alias cvenv="python -m venv .venv"
  alias fzfpip="pip freeze | fzf"
  alias fzfuvpip="uv pip freeze | fzf"

  EOF

  source ~/.bashrc

  echo -e "\n=========   Creating .bash_profile file...   =========\n"
  cat << 'EOF' > ~/.bash_profile
  #!/usr/bin/env bash

  if [ -f ~/.bashrc ]; then
      source ~/.bashrc
  fi

  EOF

  echo -e "\n=========   Installing apt-get libraries...   =========\n"
  sudo apt-get update
  sudo apt-get install -y fzf

  echo -e "\n=========   Installing uv...   =========\n"
  curl -LsSf https://astral.sh/uv/install.sh | sh

  echo -e "\n===============   SKYPILOT SETUP COMPLETE   ===============\n"